---
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'mvp'
            
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets: ['prometheus:9090']
                             
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'jenkins_exporter'
    metrics_path: /jenkins/prometheus/
    static_configs:
      - targets: ['jenkins:8080']

rule_files:
  - 'alert.rules'
  